### ISSUE TITLE
Manual action required for both S3 assets buckets to config aws_s3_bucket_acl

### ISSUE THREAD

**Issue by emyriounis** [Nexode-Consulting/terraform-aws-nextjs-serverless#1]
Error: creating S3 bucket ACL for {{deployment_name}}-public-assets: AccessControlListNotSupported: The bucket does not allow ACLs

`with module.next_serverless.module.static-deploy.module.static_assets_bucket.aws_s3_bucket_acl.this[0],
│   on .terraform/modules/next_serverless.static-deploy.static_assets_bucket/main.tf line 45, in resource "aws_s3_bucket_acl" "this":
│   45: resource "aws_s3_bucket_acl" "this" {`

**Comment by muratcanozdemir** [comment]
Check this out: [https://github.com/Nexode-Consulting/terraform-aws-nextjs-serverless/commit/ec94f9f05f6eb055410fe0ff6e4f2efb8341c982](url) @emyriounis

**Comment by emyriounis** [comment]
This issue was fixed by #5
